openapi: "3.0"
info:
  title: Personal Shopper API
  description: Personal Shopper 내부 API
  version: 0.0.1

servers:
#  - url: https://real/v1
#    description: Production server
  - url: http://devapi.ap-northeast-2.elasticbeanstalk.com/
    description: Development server

tags:
  - name: Auth
    description: 로그인 관련

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid

paths:
  /auth:
    post:
      summary: Get Auth Tokens
      description: Get Access Token & Refresh Token
      tags: [ Auth ]
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  type: string
                  enum: [ refresh, naver, kakao ]
                  required: true
                code:
                  type: string
                  description: Refresh Token 또는 서드파티 Auth 코드
                  required: true
      #            examples:
      #              user:
      #                summary: User Example
      #                externalValue: 'http://foo.bar/examples/user-example.json'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  refreshToken:
                    type: string
                    description: 필요 할 때만 나옴
        '400':
          description: code is invalid
  /auth/test:
    get:
      summary: Test API
      description: 로그인이 잘 되었는지 확인 하는 API
      tags: [ Auth ]
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: OK
        '401':
          $ref: '#/components/responses/UnauthorizedError'

