openapi: "3.0.0"
info:
  title: Personal Shopper API
  description: Personal Shopper 내부 API
  version: 0.0.1

servers:
  - url: https://real/v1
    description: Production server
  - url: http://devapi.ap-northeast-2.elasticbeanstalk.com/v1
    description: Development server

tags:
  - name: Auth
    description: 로그인 관련


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  Errors:
    UnauthorizedError:
      description: Access token is missing or invalid
    ParameterError:
      description: Request parameters missing or invalid

paths:
  $ref: 'auth.yaml#/path'