openapi: "3.0.0"
info:
  title: Personal Shopper API
  description: Personal Shopper 내부 API
  version: 0.0.1

servers:
  - url: https://real/v1
    description: Production server
  - url: http://devapi.ap-northeast-2.elasticbeanstalk.com/v1
    description: Development server

tags:
  - name: Auth
    description: 로그인 관련
  - name: Home
    description: 홈 화면 관련
  - name: Onboard
    description: 온보딩 관련
  - name: Profile
    description: 프로필 관련
  - name: StyleType
    description: Style Type 관련
  - name: Supplier
    description: Supplier 관련 정보


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        payload

        ```json
        {
          "userId": "number",
          "gender": "F|M",
          "userType": "N|D|S|W"
        }
        ```

        userType은
          * N: 미등록
          * D: 일반 유저
          * S: 스타일리스트
          * W: 스타일리스트 인가 대기
  Request:
    page:
      name: page
      in: 'query'
      description: 보고자 하는 Page Number. 0 부터 시작, 한 페이지당 20개의 데이터
      schema:
        type: number
        default: 0
  scheme:
    StyleTypeList:
      type: array
      description: Style Type 목록
      items:
        $ref: '#/components/scheme/StyleType'
    StyleType:
      type: object
      properties:
        id:
          type: number
          description: 스타일 ID
        value:
          type: string
          description: 스타일 명

  Errors:
    UnauthorizedError:
      description: Access token is missing or invalid
    ParameterError:
      description: Request parameters missing or invalid

paths:
  $ref: 'path.yaml'